version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 345657619384.dkr.ecr.us-east-1.amazonaws.com
      - echo Setting repository URI...
      - REPOSITORY_URI=345657619384.dkr.ecr.us-east-1.amazonaws.com/cicdpipeline
      - echo Setting image tag...
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo Build started on `date`
      - echo Running Maven build...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest -f store/Dockerfile store/
      - echo Tagging the Docker image...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"cicdpipeline","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json